package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

func TestUpdateAssetName(t *testing.T) {
	cases := []struct {
		goos, goarch string
		want         string
		ok           bool
	}{
		{"windows", "amd64", "dsh-launcher-windows-amd64.exe", true},
		{"darwin", "arm64", "dsh-launcher-darwin-arm64.zip", true},
		{"darwin", "amd64", "dsh-launcher-darwin-amd64.zip", true},
		{"linux", "amd64", "dsh-launcher-linux-amd64.tar.gz", true},
		{"windows", "arm64", "", false}, // CI 没产出这个组合 → 只能走下载页
		{"linux", "arm64", "", false},
	}
	for _, c := range cases {
		got, ok := updateAssetName(c.goos, c.goarch)
		if got != c.want || ok != c.ok {
			t.Errorf("updateAssetName(%s/%s) = (%q,%v), want (%q,%v)", c.goos, c.goarch, got, ok, c.want, c.ok)
		}
	}
}

func TestBuildLauncherReleaseHasUpdate(t *testing.T) {
	rel := &ghRelease{
		TagName:     "v0.6.0",
		Name:        "v0.6.0",
		Body:        "  本轮变化：…  ",
		PublishedAt: "2026-09-13T05:57:11Z",
		HTMLURL:     "https://github.com/wishesl/dsh-launcher/releases/tag/v0.6.0",
		Assets: []ghAsset{
			{Name: "dsh-launcher-windows-amd64.exe", Size: 100, URL: "https://example.test/a.exe"},
			{Name: sumsAssetName, Size: 64, URL: "https://example.test/SHA256SUMS"},
		},
	}
	out := buildLauncherRelease(rel, "0.5.1", runtime.GOOS, runtime.GOARCH, "")
	if !out.Comparable || !out.HasUpdate {
		t.Fatalf("expected comparable+hasUpdate, got %+v", out)
	}
	if out.Latest != "0.6.0" {
		t.Errorf("Latest = %q, want 0.6.0 (v 前缀要去掉)", out.Latest)
	}
	if out.Notes != "本轮变化：…" {
		t.Errorf("Notes 应去掉首尾空白, got %q", out.Notes)
	}
	// Windows 上资产齐备 → 可应用内更新；其它平台按 updateAppliable 的结论。
	wantSupported := runtime.GOOS == "windows"
	if out.Supported != wantSupported {
		t.Errorf("Supported = %v, want %v (%s/%s)", out.Supported, wantSupported, runtime.GOOS, runtime.GOARCH)
	}
	if out.Supported && out.Asset.Name == "" {
		t.Error("Supported 为真时必须有本平台资产")
	}
	if out.sumsURL == "" {
		t.Error("应记录 SHA256SUMS 的地址（下载校验要用）")
	}
}

func TestBuildLauncherReleaseThreeStates(t *testing.T) {
	base := func() *ghRelease {
		return &ghRelease{
			TagName: "v0.6.0",
			Assets: []ghAsset{
				{Name: "dsh-launcher-windows-amd64.exe", Size: 100, URL: "https://example.test/a.exe"},
				{Name: sumsAssetName, Size: 64, URL: "https://example.test/SHA256SUMS"},
			},
		}
	}

	// ① dev 构建：不参与比较（但也别谎报"有更新"）
	dev := buildLauncherRelease(base(), "dev", runtime.GOOS, runtime.GOARCH, "")
	if dev.Comparable || dev.HasUpdate {
		t.Errorf("dev 构建不应参与比较: %+v", dev)
	}

	// ② 已是最新
	same := buildLauncherRelease(base(), "0.6.0", runtime.GOOS, runtime.GOARCH, "")
	if !same.Comparable || same.HasUpdate {
		t.Errorf("同版本不应报有更新: %+v", same)
	}

	// ③ 本地比线上新（预发布尝鲜）→ 不提示更新
	ahead := buildLauncherRelease(base(), "0.6.1", runtime.GOOS, runtime.GOARCH, "")
	if ahead.HasUpdate {
		t.Errorf("本地更高时不应报有更新: %+v", ahead)
	}

	// ④ 没有 SHA256SUMS → 不支持应用内更新，且给出人话原因
	noSums := base()
	noSums.Assets = noSums.Assets[:1]
	ns := buildLauncherRelease(noSums, "0.5.1", runtime.GOOS, runtime.GOARCH, "")
	if ns.Supported || !strings.Contains(ns.SupportNote, sumsAssetName) {
		t.Errorf("缺校验和时不该支持应用内更新: %+v", ns)
	}

	// ⑤ 用户点过「跳过此版本」
	skip := buildLauncherRelease(base(), "0.5.1", runtime.GOOS, runtime.GOARCH, "0.6.0")
	if !skip.Skipped {
		t.Errorf("skippedVersion 命中时应标记 Skipped: %+v", skip)
	}
}

func TestUpdateAppliableOnlyWindows(t *testing.T) {
	if ok, _ := updateAppliable("windows"); !ok {
		t.Error("windows 应支持就地替换")
	}
	for _, goos := range []string{"darwin", "linux"} {
		if ok, note := updateAppliable(goos); ok || note == "" {
			t.Errorf("%s 目前不支持应用内更新，且必须给出原因", goos)
		}
	}
}

func TestParseSums(t *testing.T) {
	body := strings.Join([]string{
		"# generated by CI",
		strings.Repeat("a", 64) + "  dsh-launcher-windows-amd64.exe",
		strings.Repeat("b", 64) + " *dsh-launcher-linux-amd64.tar.gz",
		strings.Repeat("c", 64) + "  ./dsh-launcher-darwin-arm64.zip",
		"deadbeef  short-hash-should-be-ignored",
	}, "\n")

	if got := parseSums(body, "dsh-launcher-windows-amd64.exe"); got != strings.Repeat("a", 64) {
		t.Errorf("windows 哈希 = %q", got)
	}
	if got := parseSums(body, "dsh-launcher-linux-amd64.tar.gz"); got != strings.Repeat("b", 64) {
		t.Errorf("带 * 前缀的二进制模式没解析出来: %q", got)
	}
	if got := parseSums(body, "dsh-launcher-darwin-arm64.zip"); got != strings.Repeat("c", 64) {
		t.Errorf("带路径前缀的条目没解析出来: %q", got)
	}
	if got := parseSums(body, "not-there.exe"); got != "" {
		t.Errorf("缺失条目应返回空串, got %q", got)
	}
}

func TestDownloadToFileHashAndSize(t *testing.T) {
	payload := bytes.Repeat([]byte("dsh-launcher"), 512)
	want := sha256.Sum256(payload)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Length", strconv.Itoa(len(payload)))
		_, _ = w.Write(payload)
	}))
	defer srv.Close()

	dest := filepath.Join(t.TempDir(), "pkg.part")
	got, err := downloadToFile(context.Background(), srv.Client(), srv.URL, dest, int64(len(payload)), nil)
	if err != nil {
		t.Fatalf("downloadToFile: %v", err)
	}
	if wantHex := hex.EncodeToString(want[:]); got != wantHex {
		t.Errorf("sha256 = %s, want %s", got, wantHex)
	}
	if st, _ := os.Stat(dest); st == nil || st.Size() != int64(len(payload)) {
		t.Errorf("落盘大小不对: %v", st)
	}

	// 期望大小与实际不符（例如被代理截断）必须报错，不能"算出一个哈希就算成功"
	if _, err := downloadToFile(context.Background(), srv.Client(), srv.URL, dest+".2", int64(len(payload)+7), nil); err == nil {
		t.Error("大小不符时应报错")
	}
}

func TestFetchExpectedSum(t *testing.T) {
	sum := strings.Repeat("d", 64)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/SHA256SUMS" {
			w.WriteHeader(http.StatusNotFound)
			return
		}
		_, _ = w.Write([]byte(sum + "  dsh-launcher-windows-amd64.exe\n"))
	}))
	defer srv.Close()

	got, err := fetchExpectedSum(context.Background(), srv.Client(), srv.URL+"/SHA256SUMS", "dsh-launcher-windows-amd64.exe")
	if err != nil || got != sum {
		t.Fatalf("fetchExpectedSum = (%q,%v)", got, err)
	}
	// 列表里没有这个资产 → 必须报错（没有校验就不装）
	if _, err := fetchExpectedSum(context.Background(), srv.Client(), srv.URL+"/SHA256SUMS", "other.exe"); err == nil {
		t.Error("找不到对应哈希时应报错")
	}
	if _, err := fetchExpectedSum(context.Background(), srv.Client(), srv.URL+"/missing", "x.exe"); err == nil {
		t.Error("HTTP 404 时应报错")
	}
}

func TestApplyUpdateExecutableSwapsAndRollsBack(t *testing.T) {
	dir := t.TempDir()
	self := filepath.Join(dir, "dsh-launcher.exe")
	newer := filepath.Join(dir, "downloaded.exe")
	if err := os.WriteFile(self, []byte("OLD"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(newer, []byte("NEW"), 0o755); err != nil {
		t.Fatal(err)
	}

	if err := applyUpdateExecutable(self, newer); err != nil {
		t.Fatalf("applyUpdateExecutable: %v", err)
	}
	got, err := os.ReadFile(self)
	if err != nil || string(got) != "NEW" {
		t.Fatalf("原路径上应是新版本, got %q err=%v", got, err)
	}

	// 回滚路径：新文件不存在 → 报错，且原路径必须还是原来的可执行文件
	if err := os.WriteFile(self, []byte("OLD"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := applyUpdateExecutable(self, filepath.Join(dir, "missing.exe")); err == nil {
		t.Fatal("新文件缺失时应报错")
	}
	got, err = os.ReadFile(self)
	if err != nil || string(got) != "OLD" {
		t.Fatalf("回滚失败：原路径应还是旧版本, got %q err=%v", got, err)
	}
	if _, err := os.Stat(self + ".old"); !os.IsNotExist(err) {
		t.Errorf("回滚后不该留下 .old: %v", err)
	}
}

func TestUpdatedFromPID(t *testing.T) {
	cases := []struct {
		args []string
		want int
	}{
		{[]string{"dsh-launcher.exe"}, 0},
		{[]string{"dsh-launcher.exe", "--updated-from=4242"}, 4242},
		{[]string{"dsh-launcher.exe", "--updated-from=0"}, 0},
		{[]string{"dsh-launcher.exe", "--updated-from=abc"}, 0},
	}
	for _, c := range cases {
		if got := updatedFromPID(c.args); got != c.want {
			t.Errorf("updatedFromPID(%v) = %d, want %d", c.args, got, c.want)
		}
	}
}

func TestHumanSize(t *testing.T) {
	cases := map[int64]string{
		0:                "未知大小",
		1536:             "2 KB",
		12 * 1024 * 1024: "12.0 MB",
	}
	for in, want := range cases {
		if got := humanSize(in); got != want {
			t.Errorf("humanSize(%d) = %q, want %q", in, got, want)
		}
	}
}

// fakeGitHub 起一个假 GitHub：/repos/o/r/releases/latest + 资产 + SHA256SUMS。
// tamper=true 时故意把校验和写错（验证"校验不过就绝不安装"）。
func fakeGitHub(t *testing.T, payload []byte, tamper bool) (base string, downloads *int32) {
	t.Helper()
	assetName, ok := updateAssetName(runtime.GOOS, runtime.GOARCH)
	if !ok {
		t.Skipf("当前平台 %s/%s 没有 CI 产物，跳过", runtime.GOOS, runtime.GOARCH)
	}
	sum := sha256.Sum256(payload)
	sumHex := hex.EncodeToString(sum[:])
	if tamper {
		sumHex = strings.Repeat("0", 64)
	}
	var hits int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/repos/o/r/releases/latest":
			_ = json.NewEncoder(w).Encode(map[string]interface{}{
				"tag_name":     "v0.6.0",
				"name":         "v0.6.0",
				"body":         "本轮变化",
				"published_at": "2026-09-13T05:57:11Z",
				"html_url":     "https://example.test/releases/tag/v0.6.0",
				"assets": []map[string]interface{}{
					{"name": assetName, "size": len(payload), "browser_download_url": "http://" + r.Host + "/dl/" + assetName},
					{"name": sumsAssetName, "size": 72, "browser_download_url": "http://" + r.Host + "/dl/" + sumsAssetName},
				},
			})
		case "/dl/" + assetName:
			atomic.AddInt32(&hits, 1)
			_, _ = w.Write(payload)
		case "/dl/" + sumsAssetName:
			_, _ = w.Write([]byte(sumHex + "  " + assetName + "\n"))
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	t.Cleanup(srv.Close)
	return srv.URL, &hits
}

// newUpdateTestApp 造一个"配置目录在临时目录里"的 App，并把包级变量临时改掉：
// 假 GitHub + 假 self（绝不能让单测把测试二进制自己替换掉）。
func newUpdateTestApp(t *testing.T, apiBase, self string) *App {
	t.Helper()
	tmp := t.TempDir()
	oldAPI, oldSelf, oldVersion := updateAPIBase, updateSelfPath, version
	updateAPIBase = apiBase
	updateSelfPath = func() (string, error) { return self, nil }
	version = "0.5.1"
	oldApplied := updateApplied.Load()
	t.Cleanup(func() {
		updateAPIBase, updateSelfPath, version = oldAPI, oldSelf, oldVersion
		updateApplied.Store(oldApplied)
		appliedVersion.Store("")
		updCache.Lock()
		updCache.release, updCache.etag, updCache.at = nil, "", time.Time{}
		updCache.Unlock()
	})
	a := &App{
		settings: &settingsStore{path: filepath.Join(tmp, "settings.json")},
		store:    &instanceStore{path: filepath.Join(tmp, "instances.json")},
	}
	a.settings.setUpdateSettings(true, false, "", "o/r")
	return a
}

// TestUpdateFullFlow 跑完整链路：检查 → 下载 → sha256 校验 → 就地替换 → "已就位"。
// 这是 M2 的核心验收（真机上再跑一次，见方案 §7）。
func TestUpdateFullFlow(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("应用内就地替换目前只在 Windows 实现（M4 才做跨平台）")
	}
	payload := []byte("NEW-LAUNCHER-BINARY-PAYLOAD")
	base, downloads := fakeGitHub(t, payload, false)

	self := filepath.Join(t.TempDir(), "dsh-launcher.exe")
	if err := os.WriteFile(self, []byte("OLD-BINARY"), 0o755); err != nil {
		t.Fatal(err)
	}
	a := newUpdateTestApp(t, base, self)

	rel := a.CheckLauncherUpdate(true)
	if rel.Err != "" {
		t.Fatalf("检查更新失败: %s", rel.Err)
	}
	if !rel.HasUpdate || !rel.Comparable {
		t.Fatalf("应判定为有更新: %+v", rel)
	}
	if !rel.Supported || rel.Asset.Name == "" {
		t.Fatalf("资产齐备时应支持应用内更新: %+v", rel)
	}
	if rel.Latest != "0.6.0" || rel.Current != "0.5.1" {
		t.Fatalf("版本号解析不对: %+v", rel)
	}

	if err := a.DownloadLauncherUpdate(); err != nil {
		t.Fatalf("下载安装失败: %v", err)
	}
	got, err := os.ReadFile(self)
	if err != nil {
		t.Fatalf("替换后读不到 exe: %v", err)
	}
	if !bytes.Equal(got, payload) {
		t.Fatalf("exe 未被替换成新版本: %q", got)
	}
	if n := atomic.LoadInt32(downloads); n != 1 {
		t.Errorf("资产应只下载一次, got %d", n)
	}
	if v := a.UpdateAppliedVersion(); v != "0.6.0" {
		t.Errorf("已就位版本 = %q, want 0.6.0", v)
	}
	if a.UpdateOpRunning() {
		t.Error("结束之后不该还显示运行中")
	}
}

// TestUpdateRefusesBadChecksum 校验和不对时必须拒绝安装，并且**不动**原 exe。
func TestUpdateRefusesBadChecksum(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("应用内就地替换目前只在 Windows 实现")
	}
	payload := []byte("TAMPERED-PAYLOAD")
	base, _ := fakeGitHub(t, payload, true)

	self := filepath.Join(t.TempDir(), "dsh-launcher.exe")
	if err := os.WriteFile(self, []byte("OLD-BINARY"), 0o755); err != nil {
		t.Fatal(err)
	}
	a := newUpdateTestApp(t, base, self)

	if err := a.DownloadLauncherUpdate(); err == nil {
		t.Fatal("校验和不匹配时必须报错")
	}
	got, err := os.ReadFile(self)
	if err != nil || string(got) != "OLD-BINARY" {
		t.Fatalf("校验失败时不该动原 exe, got %q err=%v", got, err)
	}
	if v := a.UpdateAppliedVersion(); v != "" {
		t.Errorf("校验失败不该标记已就位, got %q", v)
	}
}
