// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:main.FavoriteDraft):Promise<Array<main.FavoritePlugin>>;

export function ApproveBuilds(arg1:Array<string>):Promise<void>;

export function CancelMarketOp():Promise<boolean>;

export function CheckEnvironment():Promise<main.EnvReport>;

export function DetectLocalVersion(arg1:string):Promise<string>;

export function DirectoryExists(arg1:string):Promise<boolean>;

export function EnsureConfigDir():Promise<void>;

export function FetchMarketCatalog(arg1:boolean):Promise<main.MarketCatalog>;

export function GenerateShareCode(arg1:Array<string>):Promise<string>;

export function GetAppDataPath():Promise<string>;

export function GetInstanceMasks(arg1:string):Promise<Array<string>>;

export function GetInstances():Promise<Array<main.Instance>>;

export function GetMarketSettings():Promise<main.MarketSettings>;

export function GetProxySettings():Promise<main.ProxySettings>;

export function HideToTray():Promise<void>;

export function ImportShareCode(arg1:string,arg2:Array<string>):Promise<main.ShareImportResult>;

export function InstallFavorite(arg1:string,arg2:main.FavoritePlugin):Promise<main.MarketOpResult>;

export function InstallPlugin(arg1:string,arg2:string):Promise<main.MarketOpResult>;

export function InstallPnpm():Promise<void>;

export function InstallToDirectory(arg1:string):Promise<Array<main.Instance>>;

export function LaunchInstance(arg1:string):Promise<void>;

export function ListFavorites():Promise<Array<main.FavoritePlugin>>;

export function ListInstalledPlugins():Promise<Array<main.InstalledPlugin>>;

export function MarketOpRunning():Promise<boolean>;

export function ParseShareCode(arg1:string):Promise<main.ShareImportResult>;

export function ProbeServices():Promise<Array<main.ServiceState>>;

export function QueryLatestVersion():Promise<string>;

export function QueryRegistry():Promise<main.RegistryInfo>;

export function QuitApp():Promise<void>;

export function RemoveFavorite(arg1:string):Promise<Array<main.FavoritePlugin>>;

export function RemoveInstance(arg1:string):Promise<Array<main.Instance>>;

export function RequestClose():Promise<void>;

export function RunAutoStartInstances():Promise<Array<string>>;

export function SaveInstance(arg1:main.Instance):Promise<Array<main.Instance>>;

export function SelectDirectory():Promise<string>;

export function SetAutoStart(arg1:string,arg2:boolean):Promise<Array<main.Instance>>;

export function SetInstanceMasks(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function SetMarketRegistryURL(arg1:string):Promise<void>;

export function SetProxy(arg1:string):Promise<void>;

export function SortInstances():Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function TogglePlugin(arg1:string,arg2:boolean):Promise<void>;

export function UninstallPlugin(arg1:string,arg2:string):Promise<main.MarketOpResult>;
