// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectLocalVersion(arg1:string):Promise<string>;

export function DirectoryExists(arg1:string):Promise<boolean>;

export function EnsureConfigDir():Promise<void>;

export function GetAppDataPath():Promise<string>;

export function GetCloseToTray():Promise<boolean>;

export function GetInstances():Promise<Array<main.Instance>>;

export function HideToTray():Promise<void>;

export function InstallToDirectory(arg1:string):Promise<Array<main.Instance>>;

export function LaunchInstance(arg1:string):Promise<void>;

export function QueryLatestVersion():Promise<string>;

export function QueryRegistry():Promise<main.RegistryInfo>;

export function RemoveInstance(arg1:string):Promise<Array<main.Instance>>;

export function RunAutoStartInstances():Promise<Array<string>>;

export function SaveInstance(arg1:main.Instance):Promise<Array<main.Instance>>;

export function SelectDirectory():Promise<string>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SortInstances():Promise<void>;

export function StopInstance(arg1:string):Promise<void>;
