// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function DetectLocalVersion(arg1) {
  return window['go']['main']['App']['DetectLocalVersion'](arg1);
}

export function DirectoryExists(arg1) {
  return window['go']['main']['App']['DirectoryExists'](arg1);
}

export function EnsureConfigDir() {
  return window['go']['main']['App']['EnsureConfigDir']();
}

export function GetAppDataPath() {
  return window['go']['main']['App']['GetAppDataPath']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function InstallPnpm() {
  return window['go']['main']['App']['InstallPnpm']();
}

export function InstallToDirectory(arg1) {
  return window['go']['main']['App']['InstallToDirectory'](arg1);
}

export function LaunchInstance(arg1) {
  return window['go']['main']['App']['LaunchInstance'](arg1);
}

export function QueryLatestVersion() {
  return window['go']['main']['App']['QueryLatestVersion']();
}

export function QueryRegistry() {
  return window['go']['main']['App']['QueryRegistry']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveInstance(arg1) {
  return window['go']['main']['App']['RemoveInstance'](arg1);
}

export function RunAutoStartInstances() {
  return window['go']['main']['App']['RunAutoStartInstances']();
}

export function SaveInstance(arg1) {
  return window['go']['main']['App']['SaveInstance'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetAutoStart(arg1, arg2) {
  return window['go']['main']['App']['SetAutoStart'](arg1, arg2);
}

export function SortInstances() {
  return window['go']['main']['App']['SortInstances']();
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}
